package com.dbquery.components;

import java.io.InputStream;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;
import javax.swing.JTree;
import javax.swing.tree.DefaultMutableTreeNode;

import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

public class TreeView extends javax.swing.JPanel {

    /** Creates new form TreeView */

    public TreeView() {
        initComponents();
        init();
    }

    private void init() {
    	
		
    }
    public JTree getTreeView(String contents) {
    	return 	getTreeView(null, contents);
    }
    public JTree getTreeView(InputStream is) {
    	return 	getTreeView(is, null);
    }
    
    private JTree getTreeView(InputStream is, String contents) {
        try {
            //Decoder decoder = new Decoder(is);
            //decoder.parse();
            if (contents == null)
            	contents = Helper.getInputStreamContents(is);
            
            JSONObject object = null;
            JSONArray array = null;
            
            try {            
                object = new JSONObject(contents);
            } catch(JSONException e) {
                try {
                    array = new JSONArray(contents);
                } catch(JSONException je) {                    
                }
            } finally {
                if(object == null && array == null) {
                    //JOptionPane.showMessageDialog(this, "The Source specified does not contain a valid JSON String", "Error", JOptionPane.ERROR_MESSAGE);
                	return null;
                }
            }
            DefaultMutableTreeNode node = new DefaultMutableTreeNode("Case");
            if (array == null) {
                HashMap<String, Object> fm = Helper.getMapFromJSONObject(object);
                Helper.getNodeFromMap(fm, node);
                jsonTree = new JTree(node);
            } else {
                ArrayList<Object> list = Helper.getListFromJSONArray(array);
                Helper.getNodeFromList(list, node);
                jsonTree = new JTree(node);
            }
        } catch (JSONException ex) {
            Logger.getLogger(TreeView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(TreeView.class.getName()).log(Level.SEVERE, null, ex);
        }
        return jsonTree;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        treeScrollPane = new javax.swing.JScrollPane();
        jsonTree = new javax.swing.JTree();

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        jsonTree.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        treeScrollPane.setViewportView(jsonTree);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(treeScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 586, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(treeScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree jsonTree;
    private javax.swing.JScrollPane treeScrollPane;
    // End of variables declaration//GEN-END:variables
    
    public static void main(String[] args) {
    	new TreeView();
	}
}

